global using System;
global using System.IO;
global using System.Collections.Generic;
//global using System.Linq;
//global using System.Text;
global using Serilog;
global using Serilog.Events;
global using COMContract;
global using HcExcelAddIn.Views;
global using HcExcelAddIn.Abstractions;
global using HcExcelAddIn.Controllers;
global using HcExcelAddIn.Extensions;
global using ExcelApplication = Microsoft.Office.Interop.Excel.Application;
global using Microsoft.Extensions.DependencyInjection;
