global using System;
global using System.IO;
global using System.Collections.Generic;
//global using System.Linq;
//global using System.Text;
global using Serilog;
global using Serilog.Events;
global using COMContract;
global using HcExcelAddIn.Views;
global using XlApplication = Microsoft.Office.Interop.Excel.Application;
